// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Mon Jun 20 02:56:59 2022

CU_SelectionSort CU_SelectionSort_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.run(run_sig) ,	// input  run_sig
	.end_load(end_load_sig) ,	// input  end_load_sig
	.hit_i(hit_i_sig) ,	// input  hit_i_sig
	.hit_j(hit_j_sig) ,	// input  hit_j_sig
	.end_show(end_show_sig) ,	// input  end_show_sig
	.swap(swap_sig) ,	// output  swap_sig
	.PS(PS_sig) 	// output [2:0] PS_sig
);

